<?xml version='1.0' encoding='UTF-8'?><acquisitions><acquisition>
    <global_id>20110203173134-825-803</global_id>
    <name>LF-1916</name>
    <device>SIRA Thermo-Fisher MAT253</device>
    <technique>mass spectrometry with dual inlet</technique>
    <operator>Ryoji Tanaka</operator>
    <sample_global_id>20110203173024-157-542</sample_global_id>
    <sample_name>Dhofar 018</sample_name>
    <description>Run#1916, 1.46mg, Leached with 0.6M HCl for 2 min.</description>
    <chemistries>
      <analysis>
        <nickname>d17O</nickname>
        <value>1.805</value>
        <unit>milli</unit>
        <uncertainty>0.104</uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>d18O</nickname>
        <value>3.956</value>
        <unit>milli</unit>
        <uncertainty>0.046</uncertainty>
        <label/>
        <info/>
      </analysis>
    </chemistries>
  </acquisition><acquisition>
    <global_id>20110203173314-707-331</global_id>
    <name>LF-1918</name>
    <device>SIRA Thermo-Fisher MAT253</device>
    <technique>mass spectrometry with dual inlet</technique>
    <operator>Ryoji Tanaka</operator>
    <sample_global_id>20110203173024-157-542</sample_global_id>
    <sample_name>Dhofar 018</sample_name>
    <description>Run#1918, 1.83mg, Leached with 0.6M HCl for 2 min.</description>
    <chemistries>
      <analysis>
        <nickname>d17O</nickname>
        <value>1.64</value>
        <unit>milli</unit>
        <uncertainty>0.08</uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>d18O</nickname>
        <value>3.694</value>
        <unit>milli</unit>
        <uncertainty>0.054</uncertainty>
        <label/>
        <info/>
      </analysis>
    </chemistries>
  </acquisition><acquisition>
    <global_id>20140709093700-124563</global_id>
    <name>Dhofar 018</name>
    <device>ICPMS Agilent 7500cs</device>
    <technique>ICPMS (0)</technique>
    <operator>Marian</operator>
    <sample_global_id>20110203173024-157-542</sample_global_id>
    <sample_name>Dhofar 018</sample_name>
    <description/>
    <chemistries>
      <analysis>
        <nickname>Be</nickname>
        <value>0.053</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Li</nickname>
        <value>4.24</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Rb</nickname>
        <value>0.306</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Sr</nickname>
        <value>415.0</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Y</nickname>
        <value>2.4</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Cs</nickname>
        <value>0.021</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Ba</nickname>
        <value>67.4</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>La</nickname>
        <value>0.492</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Ce</nickname>
        <value>1.15</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Pr</nickname>
        <value>0.16</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Nd</nickname>
        <value>0.836</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Sm</nickname>
        <value>0.256</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Eu</nickname>
        <value>0.23</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Gd</nickname>
        <value>0.361</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Tb</nickname>
        <value>0.063</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Dy</nickname>
        <value>0.42</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Ho</nickname>
        <value>0.094</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Er</nickname>
        <value>0.282</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Tm</nickname>
        <value>0.042</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Yb</nickname>
        <value>0.286</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Lu</nickname>
        <value>0.045</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Pb</nickname>
        <value>0.87</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Th</nickname>
        <value>0.049</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>U</nickname>
        <value>0.235</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>B</nickname>
        <value>16.1</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Zr</nickname>
        <value>4.32</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Hf</nickname>
        <value>0.138</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Nb</nickname>
        <value>0.315</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Ta</nickname>
        <value>0.016</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
    </chemistries>
  </acquisition><acquisition>
    <global_id>20140709093636-341020</global_id>
    <name>DaG 779</name>
    <device>ICPMS Agilent 7500cs</device>
    <technique>ICPMS (0)</technique>
    <operator>Marian</operator>
    <sample_global_id>20130313090348-577-638</sample_global_id>
    <sample_name>DaG 779</sample_name>
    <description/>
    <chemistries>
      <analysis>
        <nickname>Be</nickname>
        <value>0.044</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Li</nickname>
        <value>3.69</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Rb</nickname>
        <value>0.053</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Sr</nickname>
        <value>21.6</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Y</nickname>
        <value>2.73</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Cs</nickname>
        <value>0.001</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Ba</nickname>
        <value>16.9</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>La</nickname>
        <value>0.384</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Ce</nickname>
        <value>1.01</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Pr</nickname>
        <value>0.146</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Nd</nickname>
        <value>0.801</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Sm</nickname>
        <value>0.255</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Eu</nickname>
        <value>0.093</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Gd</nickname>
        <value>0.386</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Tb</nickname>
        <value>0.069</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Dy</nickname>
        <value>0.496</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Ho</nickname>
        <value>0.109</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Er</nickname>
        <value>0.334</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Tm</nickname>
        <value>0.049</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Yb</nickname>
        <value>0.34</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Lu</nickname>
        <value>0.055</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Pb</nickname>
        <value>0.206</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Th</nickname>
        <value>0.052</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>U</nickname>
        <value>0.02</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>B</nickname>
        <value>1.24</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Zr</nickname>
        <value>5.85</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Hf</nickname>
        <value>0.178</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Nb</nickname>
        <value>0.431</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Ta</nickname>
        <value>0.021</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
    </chemistries>
  </acquisition><acquisition>
    <global_id>20110203172730-984-276</global_id>
    <name>LF-1912</name>
    <device>SIRA Thermo-Fisher MAT253</device>
    <technique>mass spectrometry with dual inlet</technique>
    <operator>Ryoji Tanaka</operator>
    <sample_global_id>20110203172626-290-792</sample_global_id>
    <sample_name>Dar al Gani 779</sample_name>
    <description>Run#1912, 1.68mg, Leached with 0.6M HCl for 2 min.</description>
    <chemistries>
      <analysis>
        <nickname>d17O</nickname>
        <value>1.601</value>
        <unit>milli</unit>
        <uncertainty>0.076</uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>d18O</nickname>
        <value>3.528</value>
        <unit>milli</unit>
        <uncertainty>0.036</uncertainty>
        <label/>
        <info/>
      </analysis>
    </chemistries>
  </acquisition><acquisition>
    <global_id>20110203172914-024-060</global_id>
    <name>LF-1914</name>
    <device>SIRA Thermo-Fisher MAT253</device>
    <technique>mass spectrometry with dual inlet</technique>
    <operator>Ryoji Tanaka</operator>
    <sample_global_id>20110203172626-290-792</sample_global_id>
    <sample_name>Dar al Gani 779</sample_name>
    <description>Run#1914, 2.16mg, Leached with 0.6M HCl for 2 min.</description>
    <chemistries>
      <analysis>
        <nickname>d17O</nickname>
        <value>1.362</value>
        <unit>milli</unit>
        <uncertainty>0.174</uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>d18O</nickname>
        <value>3.055</value>
        <unit>milli</unit>
        <uncertainty>0.042</uncertainty>
        <label/>
        <info/>
      </analysis>
    </chemistries>
  </acquisition><acquisition>
    <global_id>20110205104819-808-451</global_id>
    <name>LF-1908</name>
    <device>SIRA Thermo-Fisher MAT253</device>
    <technique>mass spectrometry with dual inlet</technique>
    <operator>Ryoji Tanaka</operator>
    <sample_global_id>20110205104605-781-051</sample_global_id>
    <sample_name>NWA 1182-b</sample_name>
    <description>Run#1908, 1.93mg, Leached with 0.6M HCl for 2 min.</description>
    <chemistries>
      <analysis>
        <nickname>d17O</nickname>
        <value>1.662</value>
        <unit>milli</unit>
        <uncertainty>0.106</uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>d18O</nickname>
        <value>3.59</value>
        <unit>milli</unit>
        <uncertainty>0.05</uncertainty>
        <label/>
        <info/>
      </analysis>
    </chemistries>
  </acquisition><acquisition>
    <global_id>20110205104702-960-486</global_id>
    <name>LF-1906</name>
    <device>SIRA Thermo-Fisher MAT253</device>
    <technique>mass spectrometry with dual inlet</technique>
    <operator>Ryoji Tanaka</operator>
    <sample_global_id>20110205104605-781-051</sample_global_id>
    <sample_name>NWA 1182-b</sample_name>
    <description>Run#1906, 1.24mg, Leached with 0.6M HCl for 2 min.</description>
    <chemistries>
      <analysis>
        <nickname>d17O</nickname>
        <value>1.691</value>
        <unit>milli</unit>
        <uncertainty>0.07</uncertainty>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>d18O</nickname>
        <value>3.672</value>
        <unit>milli</unit>
        <uncertainty>0.058</uncertainty>
        <label/>
        <info/>
      </analysis>
    </chemistries>
  </acquisition><acquisition>
    <global_id>20140709093613-014961</global_id>
    <name>NWA 1182</name>
    <device>ICPMS Agilent 7500cs</device>
    <technique>ICPMS (0)</technique>
    <operator>Marian</operator>
    <sample_global_id>20110205104605-781-051</sample_global_id>
    <sample_name>NWA 1182-b</sample_name>
    <description/>
    <chemistries>
      <analysis>
        <nickname>Be</nickname>
        <value>0.238</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Li</nickname>
        <value>6.44</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Rb</nickname>
        <value>0.241</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Sr</nickname>
        <value>67.5</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Y</nickname>
        <value>14.5</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Cs</nickname>
        <value>0.008</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Ba</nickname>
        <value>31.4</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>La</nickname>
        <value>2.48</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Ce</nickname>
        <value>6.76</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Pr</nickname>
        <value>0.959</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Nd</nickname>
        <value>5.11</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Sm</nickname>
        <value>1.594</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Eu</nickname>
        <value>0.498</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Gd</nickname>
        <value>2.27</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Tb</nickname>
        <value>0.408</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Dy</nickname>
        <value>2.77</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Ho</nickname>
        <value>0.596</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Er</nickname>
        <value>1.74</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Tm</nickname>
        <value>0.251</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Yb</nickname>
        <value>1.646</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Lu</nickname>
        <value>0.253</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Pb</nickname>
        <value>0.227</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Th</nickname>
        <value>0.32</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>U</nickname>
        <value>0.093</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>B</nickname>
        <value>0.653</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Zr</nickname>
        <value>32.5</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Hf</nickname>
        <value>0.958</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Nb</nickname>
        <value>2.69</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Ta</nickname>
        <value>0.129</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
    </chemistries>
  </acquisition></acquisitions>
