<?xml version='1.0' encoding='UTF-8'?><acquisitions><acquisition>
    <global_id>20090423092744982.hkitagawa</global_id>
    <name>Elemental and isotopic abundance of I1501</name>
    <device/>
    <technique/>
    <operator/>
    <sample_global_id>20080616170000.hk</sample_global_id>
    <sample_name>I1501</sample_name>
    <description/>
    <chemistries>
      <analysis>
        <nickname>SiO2</nickname>
        <value>47.7</value>
        <unit>cg/g</unit>
        <uncertainty/>
        <label>\abundance{SiO_{2}}</label>
        <info>abundance of {SiO_{2}}</info>
      </analysis>
      <analysis>
        <nickname>Al2O3</nickname>
        <value>13.83</value>
        <unit>cg/g</unit>
        <uncertainty/>
        <label>\abundance{Al_{2}O_{3}}</label>
        <info>abundance of {Al_{2}O_{3}}</info>
      </analysis>
      <analysis>
        <nickname>CaO</nickname>
        <value>9.8</value>
        <unit>cg/g</unit>
        <uncertainty/>
        <label>\abundance{CaO}</label>
        <info>abundance of {CaO}</info>
      </analysis>
      <analysis>
        <nickname>MgO</nickname>
        <value>4.81</value>
        <unit>cg/g</unit>
        <uncertainty/>
        <label>\abundance{MgO}</label>
        <info>abundance of {MgO}</info>
      </analysis>
      <analysis>
        <nickname>Fe2O3</nickname>
        <value>7.63</value>
        <unit>cg/g</unit>
        <uncertainty/>
        <label>\abundance{Fe_{2}O_{3}}</label>
        <info>abundance of {Fe_{2}O_{3}}</info>
      </analysis>
      <analysis>
        <nickname>FeO</nickname>
        <value>7.28</value>
        <unit>cg/g</unit>
        <uncertainty/>
        <label>\abundance{FeO}</label>
        <info>abundance of {FeO}</info>
      </analysis>
      <analysis>
        <nickname>Na2O</nickname>
        <value>2.99</value>
        <unit>cg/g</unit>
        <uncertainty/>
        <label>\abundance{Na_{2}O}</label>
        <info>abundance of {Na_{2}O}</info>
      </analysis>
      <analysis>
        <nickname>H2O+</nickname>
        <value>1.83</value>
        <unit>cg/g</unit>
        <uncertainty/>
        <label>\abundance{H_{2}O^{+}}</label>
        <info>abundance of {H_{2}O^{+}}</info>
      </analysis>
      <analysis>
        <nickname>TiO2</nickname>
        <value>3.28</value>
        <unit>cg/g</unit>
        <uncertainty/>
        <label>\abundance{TiO_{2}}</label>
        <info>abundance of {TiO_{2}}</info>
      </analysis>
      <analysis>
        <nickname>K2O</nickname>
        <value>0.5</value>
        <unit>cg/g</unit>
        <uncertainty/>
        <label>\abundance{K_{2}O}</label>
        <info>abundance of {K_{2}O}</info>
      </analysis>
      <analysis>
        <nickname>P2O5</nickname>
        <value>0.47</value>
        <unit>cg/g</unit>
        <uncertainty/>
        <label>\abundance{P_{2}O_{5}}</label>
        <info>abundance of {P_{2}O_{5}}</info>
      </analysis>
      <analysis>
        <nickname>MnO</nickname>
        <value>0.25</value>
        <unit>cg/g</unit>
        <uncertainty/>
        <label>\abundance{MnO}</label>
        <info>abundance of {MnO}</info>
      </analysis>
      <analysis>
        <nickname>Sr</nickname>
        <value>327.0</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{Sr}</label>
        <info>abundance of {Sr}</info>
      </analysis>
      <analysis>
        <nickname>Ba</nickname>
        <value>186.0</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{Ba}</label>
        <info>abundance of {Ba}</info>
      </analysis>
      <analysis>
        <nickname>Cr</nickname>
        <value>41.9</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{Cr}</label>
        <info>abundance of {Cr}</info>
      </analysis>
      <analysis>
        <nickname>Ni</nickname>
        <value>29.4</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{Ni}</label>
        <info>abundance of {Ni}</info>
      </analysis>
      <analysis>
        <nickname>Zr</nickname>
        <value>244.0</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{Zr}</label>
        <info>abundance of {Zr}</info>
      </analysis>
      <analysis>
        <nickname>Nb</nickname>
        <value>22.7</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{Nb}</label>
        <info>abundance of {Nb}</info>
      </analysis>
      <analysis>
        <nickname>Ce</nickname>
        <value>59.9</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{Ce}</label>
        <info>abundance of {Ce}</info>
      </analysis>
      <analysis>
        <nickname>La</nickname>
        <value>24.6</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{La}</label>
        <info>abundance of {La}</info>
      </analysis>
      <analysis>
        <nickname>Rb</nickname>
        <value>4.12</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{Rb}</label>
        <info>abundance of {Rb}</info>
      </analysis>
      <analysis>
        <nickname>Nd</nickname>
        <value>37.1</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{Nd}</label>
        <info>abundance of {Nd}</info>
      </analysis>
      <analysis>
        <nickname>Y</nickname>
        <value>51.9</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{Y}</label>
        <info>abundance of {Y}</info>
      </analysis>
      <analysis>
        <nickname>Pr</nickname>
        <value>8.16</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{Pr}</label>
        <info>abundance of {Pr}</info>
      </analysis>
      <analysis>
        <nickname>Th</nickname>
        <value>2.37</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{Th}</label>
        <info>abundance of {Th}</info>
      </analysis>
      <analysis>
        <nickname>Li</nickname>
        <value>5.55</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{Li}</label>
        <info>abundance of {Li}</info>
      </analysis>
      <analysis>
        <nickname>Sm</nickname>
        <value>9.01</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{Sm}</label>
        <info>abundance of {Sm}</info>
      </analysis>
      <analysis>
        <nickname>Gd</nickname>
        <value>9.42</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{Gd}</label>
        <info>abundance of {Gd}</info>
      </analysis>
      <analysis>
        <nickname>Ta</nickname>
        <value>1.42</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{Ta}</label>
        <info>abundance of {Ta}</info>
      </analysis>
      <analysis>
        <nickname>Dy</nickname>
        <value>9.18</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{Dy}</label>
        <info>abundance of {Dy}</info>
      </analysis>
      <analysis>
        <nickname>Hf</nickname>
        <value>6.22</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{Hf}</label>
        <info>abundance of {Hf}</info>
      </analysis>
      <analysis>
        <nickname>Pb</nickname>
        <value>2.04</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{Pb}</label>
        <info>abundance of {Pb}</info>
      </analysis>
      <analysis>
        <nickname>Er</nickname>
        <value>4.53</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{Er}</label>
        <info>abundance of {Er}</info>
      </analysis>
      <analysis>
        <nickname>Yb</nickname>
        <value>4.46</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{Yb}</label>
        <info>abundance of {Yb}</info>
      </analysis>
      <analysis>
        <nickname>Eu</nickname>
        <value>3.01</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{Eu}</label>
        <info>abundance of {Eu}</info>
      </analysis>
      <analysis>
        <nickname>U</nickname>
        <value>0.72</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{U}</label>
        <info>abundance of {U}</info>
      </analysis>
      <analysis>
        <nickname>Ho</nickname>
        <value>1.86</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{Ho}</label>
        <info>abundance of {Ho}</info>
      </analysis>
      <analysis>
        <nickname>Tb</nickname>
        <value>1.54</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{Tb}</label>
        <info>abundance of {Tb}</info>
      </analysis>
      <analysis>
        <nickname>Cs</nickname>
        <value>0.152</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{Cs}</label>
        <info>abundance of {Cs}</info>
      </analysis>
      <analysis>
        <nickname>Tm</nickname>
        <value>0.662</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{Tm}</label>
        <info>abundance of {Tm}</info>
      </analysis>
      <analysis>
        <nickname>Lu</nickname>
        <value>0.618</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{Lu}</label>
        <info>abundance of {Lu}</info>
      </analysis>
      <analysis>
        <nickname>B</nickname>
        <value>1.37</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label>\abundance{B}</label>
        <info>abundance of {B}</info>
      </analysis>
      <analysis>
        <nickname>Sr87zSr86</nickname>
        <value>0.703449</value>
        <unit/>
        <uncertainty/>
        <label>\abundance{^{87}Sr}/{^{86}Sr}</label>
        <info>abundance of {^{87}Sr}/{^{86}Sr}</info>
      </analysis>
      <analysis>
        <nickname>Pb208zPb204</nickname>
        <value>38.1684</value>
        <unit/>
        <uncertainty/>
        <label>\abundance{^{208}Pb}/{^{204}Pb}</label>
        <info>abundance of {^{208}Pb}/{^{204}Pb}</info>
      </analysis>
      <analysis>
        <nickname>Hf176zHf177</nickname>
        <value>0.283178</value>
        <unit/>
        <uncertainty/>
        <label>\abundance{^{176}Hf}/{^{177}Hf}</label>
        <info>abundance of {^{176}Hf}/{^{177}Hf}</info>
      </analysis>
      <analysis>
        <nickname>Pb207zPb204</nickname>
        <value>15.4817</value>
        <unit/>
        <uncertainty/>
        <label>\abundance{^{207}Pb}/{^{204}Pb}</label>
        <info>abundance of {^{207}Pb}/{^{204}Pb}</info>
      </analysis>
      <analysis>
        <nickname>Pb206zPb204</nickname>
        <value>18.3421</value>
        <unit/>
        <uncertainty/>
        <label>\abundance{^{206}Pb}/{^{204}Pb}</label>
        <info>abundance of {^{206}Pb}/{^{204}Pb}</info>
      </analysis>
      <analysis>
        <nickname>Nd143zNd144</nickname>
        <value>0.512979</value>
        <unit/>
        <uncertainty/>
        <label>\abundance{^{143}Nd}/{^{144}Nd}</label>
        <info>abundance of {^{143}Nd}/{^{144}Nd}</info>
      </analysis>
    </chemistries>
  </acquisition><acquisition>
    <global_id>20160114184220-157191</global_id>
    <name>I1501</name>
    <device>ICPMS Thermo-Fisher Neptune</device>
    <technique>ICPMS with multi-collection</technique>
    <operator>hkitagawa</operator>
    <sample_global_id>20080616170000.hk</sample_global_id>
    <sample_name>I1501</sample_name>
    <description/>
    <chemistries>
      <analysis>
        <nickname>Hf176zHf177</nickname>
        <value>0.283178</value>
        <unit/>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
    </chemistries>
  </acquisition><acquisition>
    <global_id>20110603191650-600-883</global_id>
    <name>I1501</name>
    <device>ICPMS Yokogawa PMS2000/Agilent 7500cs</device>
    <technique>ICPMS (0)</technique>
    <operator>hkitagawa</operator>
    <sample_global_id>20080616170000.hk</sample_global_id>
    <sample_name>I1501</sample_name>
    <description>Methods applied are those described in Makishima et al. (1997, 1999), Makishima and Nakamura (1997, 2006), Yokoyama et al. (1999), Moriguti et al. (2004), and Lu et al. (2007)</description>
    <chemistries>
      <analysis>
        <nickname>Li</nickname>
        <value>5.55</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>B</nickname>
        <value>1.37</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Rb</nickname>
        <value>4.12</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Sr</nickname>
        <value>327.0</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Y</nickname>
        <value>51.9</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Zr</nickname>
        <value>244.0</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Nb</nickname>
        <value>22.7</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Cs</nickname>
        <value>0.152</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Ba</nickname>
        <value>186.0</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>La</nickname>
        <value>24.6</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Ce</nickname>
        <value>59.9</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Pr</nickname>
        <value>8.16</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Nd</nickname>
        <value>37.1</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Sm</nickname>
        <value>9.01</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Eu</nickname>
        <value>3.01</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Gd</nickname>
        <value>9.42</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Tb</nickname>
        <value>1.54</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Dy</nickname>
        <value>9.18</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Ho</nickname>
        <value>1.86</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Er</nickname>
        <value>4.53</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Tm</nickname>
        <value>0.662</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Yb</nickname>
        <value>4.46</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Lu</nickname>
        <value>0.618</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Hf</nickname>
        <value>6.22</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Ta</nickname>
        <value>1.42</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Pb</nickname>
        <value>2.04</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Th</nickname>
        <value>2.37</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>U</nickname>
        <value>0.72</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
    </chemistries>
  </acquisition><acquisition>
    <global_id>20110606083444-158-103</global_id>
    <name>I1501</name>
    <device>Microbalance/Muffle furnace ADVANTEC KM-420</device>
    <technique>gravimetry</technique>
    <operator>hkitagawa</operator>
    <sample_global_id>20080616170000.hk</sample_global_id>
    <sample_name>I1501</sample_name>
    <description>Abundance is estimated from the loss on ignition and ferric-ferrous ratio</description>
    <chemistries>
      <analysis>
        <nickname>H2O+</nickname>
        <value>1.83</value>
        <unit>cg/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
    </chemistries>
  </acquisition><acquisition>
    <global_id>20110606083622-617-356</global_id>
    <name>I1501</name>
    <device>Piston Burette Schott Titronic 96</device>
    <technique>Titration with Yokoyama and Nakamura (2002)</technique>
    <operator>hkitagawa</operator>
    <sample_global_id>20080616170000.hk</sample_global_id>
    <sample_name>I1501</sample_name>
    <description>A method applied are that described in Yokoyama and Nakamura (2002)</description>
    <chemistries>
      <analysis>
        <nickname>FeO</nickname>
        <value>7.28</value>
        <unit>cg/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
    </chemistries>
  </acquisition><acquisition>
    <global_id>20110713173726-903-108</global_id>
    <name>I1501</name>
    <device>TIMS Thermo-Fisher MAT261/262</device>
    <technique>TIMS</technique>
    <operator>hkitagawa</operator>
    <sample_global_id>20080616170000.hk</sample_global_id>
    <sample_name>I1501</sample_name>
    <description/>
    <chemistries>
      <analysis>
        <nickname>Sr87zSr86</nickname>
        <value>0.703449</value>
        <unit/>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Nd143zNd144</nickname>
        <value>0.512979</value>
        <unit/>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Pb206zPb204</nickname>
        <value>18.3421</value>
        <unit/>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Pb207zPb204</nickname>
        <value>15.4817</value>
        <unit/>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Pb208zPb204</nickname>
        <value>38.1684</value>
        <unit/>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
    </chemistries>
  </acquisition><acquisition>
    <global_id>20110602184915-337-297</global_id>
    <name>I1501</name>
    <device>XRF PANalytical PW2400</device>
    <technique>XRF (0)</technique>
    <operator>hkitagawa</operator>
    <sample_global_id>20080616170000.hk</sample_global_id>
    <sample_name>I1501</sample_name>
    <description>11-times diluted lithium tetraborate glass bead</description>
    <chemistries>
      <analysis>
        <nickname>SiO2</nickname>
        <value>47.7</value>
        <unit>cg/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>TiO2</nickname>
        <value>3.28</value>
        <unit>cg/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Al2O3</nickname>
        <value>13.83</value>
        <unit>cg/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Fe2O3T</nickname>
        <value>15.73</value>
        <unit>cg/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>MnO</nickname>
        <value>0.25</value>
        <unit>cg/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>MgO</nickname>
        <value>4.81</value>
        <unit>cg/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>CaO</nickname>
        <value>9.8</value>
        <unit>cg/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Na2O</nickname>
        <value>2.99</value>
        <unit>cg/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>K2O</nickname>
        <value>0.5</value>
        <unit>cg/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>P2O5</nickname>
        <value>0.47</value>
        <unit>cg/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Cr</nickname>
        <value>41.9</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
      <analysis>
        <nickname>Ni</nickname>
        <value>29.4</value>
        <unit>ug/g</unit>
        <uncertainty/>
        <label/>
        <info/>
      </analysis>
    </chemistries>
  </acquisition></acquisitions>
